---
version: "3.4"

services:
  app:
    container_name: lubelogger
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - data:/App/data
      - keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - nginx-managed

volumes:
  data:
  keys:

networks:
  nginx-managed:
    external: true
