---
version: "3.7"
services:
tailscale-nginx:
  image: tailscale/tailscale:v1.58
  hostname: tailscale_nginx
  environment:
    - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
    - TS_EXTRA_ARGS=--advertise-tags=tag:container
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=false
  volumes:
    - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
  devices:
    - /dev/net/tun:/dev/net/tun
  cap_add:
    - net_admin
  restart: unless-stopped
  nginx:
    image: nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
# Example from tailscale:
  # mealie:
  #   image: ghcr.io/mealie-recipes/mealie:v1.0.0
  #   container_name: mealie
  #   network_mode: service:ts-mealie
  #   depends_on:
  #     - ts-mealie
  #   volumes:
  #     - mealie-data:/app/data
  #   environment:
  #     - ALLOW_SIGNUP=true
  #   restart: unless-stopped
  lubelogger:
    image: ghcr.io/hargata/lubelogger:latest #TODO: Change to version
    # build: . #TODO: Change this to build it somewhere else, preferrably where the container is stored
    restart: unless-stopped
    depends_on:
      - tailscale-nginx
    volumes: 
    - data:/App/data
    - keys:/root/.aspnet/DataProtection-Keys
    ports:
    - 5000:8080
    # env_file: #TODO: Fix this thing, add the .env file
    network_mode: service:ll-nginx
    labels:
      

volumes:
  mealie-data:
    driver: local
  ts-mealie:
    driver: local
  lubelogger:
    driver: local
