version: "3.8"

networks:
  proxy:
    external: true

services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.grahamfam`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:
